### ISSUE TITLE
Add VOD support

### ISSUE THREAD

**Issue by Keith94** [Ew-Gr/better_twitch_chat#1]
Any chance the extension can support VODs with transitions etc.?

**Comment by Ew-Gr** [comment]
That makes me wonder how I didn't think about that before!

I'm working on it right and and I'll keep you updated about this (I'm pretty positive it's doable to be honest)

**Comment by Ew-Gr** [comment]
Quick update:

I've added a temporary solution that is pushed to the 2.1 update that you can find [here](https://github.com/Ew-Gr/better_twitch_chat/tree/master/better_twitch_chat)

I'll work on it more seriously in a week or two, right know my mind is on recovery state so I'd prefer not working too much to not have a breakdown.

So if you don't want to wait you can download the beta version adapted to your os until I work completely on it!

Thanks for the suggestion

Best,

Ewan

**Comment by Keith94** [comment]
Thanks, I'll wait to see what the final product looks like. :)
